#!/bin/bash
echo "Archiving SD video 37, Best VGM 34 - Super Mario 64 - Dire Dire Docks %slash% Jolly Roger Bay's comments (YouTube id H1B52TSCl_A...)"
python downloader.py --youtubeid="H1B52TSCl_A" --output="SD0037 Best VGM 34 - Super Mario 64 - Dire Dire Docks %slash% Jolly Roger Bay's comments (YT ID H1B52TSCl_A).json"
echo "Archiving SD video 158, Best VGM 153 - Mega Man 2 - Dr. Wily Stage 1 %slash% 2's comments (YouTube id HFKtYCcMWT4...)"
python downloader.py --youtubeid="HFKtYCcMWT4" --output="SD0158 Best VGM 153 - Mega Man 2 - Dr. Wily Stage 1 %slash% 2's comments (YT ID HFKtYCcMWT4).json"
echo "Archiving SD video 218, Best VGM 212 - Mega Man 3 - Dr. Wily Part 2 (Stage 3 %slash% 4)'s comments (YouTube id DTqp7jUBoA8...)"
python downloader.py --youtubeid="DTqp7jUBoA8" --output="SD0218 Best VGM 212 - Mega Man 3 - Dr. Wily Part 2 (Stage 3 %slash% 4)'s comments (YT ID DTqp7jUBoA8).json"
echo "Archiving SD video 292, Best VGM 281 - Pokemon Ruby %slash% Sapphire %slash% Emerald - Sootopolis City's comments (YouTube id y2MP97fwOa8...)"
python downloader.py --youtubeid="y2MP97fwOa8" --output="SD0292 Best VGM 281 - Pokemon Ruby %slash% Sapphire %slash% Emerald - Sootopolis City's comments (YT ID y2MP97fwOa8).json"
echo "Archiving SD video 390, Best VGM 379 - Mega Man 4 - Dr. Cossack Part 2 (Stage 3%slash%4)'s comments (YouTube id MlRGotA3Yzs...)"
python downloader.py --youtubeid="MlRGotA3Yzs" --output="SD0390 Best VGM 379 - Mega Man 4 - Dr. Cossack Part 2 (Stage 3%slash%4)'s comments (YT ID MlRGotA3Yzs).json"
echo "Archiving SD video 531, Best VGM 522 - Pokemon Ruby %slash% Sapphire %slash% Emerald - Rustboro City's comments (YouTube id q5vG69CXgRs...)"
python downloader.py --youtubeid="q5vG69CXgRs" --output="SD0531 Best VGM 522 - Pokemon Ruby %slash% Sapphire %slash% Emerald - Rustboro City's comments (YT ID q5vG69CXgRs).json"
echo "Archiving SD video 545, [Part 1%slash%2] Tribute to Video Game Music (2 Years Anniversary!)'s comments (YouTube id 4azKyHEjEbA...)"
python downloader.py --youtubeid="4azKyHEjEbA" --output="SD0545 [Part 1%slash%2] Tribute to Video Game Music (2 Years Anniversary!)'s comments (YT ID 4azKyHEjEbA).json"
echo "Archiving SD video 546, [Part 2%slash%2] Tribute to Video Game Music (2 Years Anniversary!)'s comments (YouTube id XBp7LEnHyHo...)"
python downloader.py --youtubeid="XBp7LEnHyHo" --output="SD0546 [Part 2%slash%2] Tribute to Video Game Music (2 Years Anniversary!)'s comments (YT ID XBp7LEnHyHo).json"
echo "Archiving SD video 658, Best VGM 625 - Wild Arms - Migrant Bird of the Wilderness (Rudy's Theme %slash% Overworld)'s comments (YouTube id DSOvrM20tMA...)"
python downloader.py --youtubeid="DSOvrM20tMA" --output="SD0658 Best VGM 625 - Wild Arms - Migrant Bird of the Wilderness (Rudy's Theme %slash% Overworld)'s comments (YT ID DSOvrM20tMA).json"
echo "Archiving SD video 733, Best VGM 701 - Super Mario Galaxy 2 - Sky Island %slash% Sky Station Galaxy 1's comments (YouTube id FCB7Dhm8RuY...)"
python downloader.py --youtubeid="FCB7Dhm8RuY" --output="SD0733 Best VGM 701 - Super Mario Galaxy 2 - Sky Island %slash% Sky Station Galaxy 1's comments (YT ID FCB7Dhm8RuY).json"
echo "Archiving SD video 772, Best VGM 740 - Pokemon Diamond %slash% Pearl %slash% Platinum - Galactic Boss Cyrus's comments (YouTube id cvpGCTUGi8o...)"
python downloader.py --youtubeid="cvpGCTUGi8o" --output="SD0772 Best VGM 740 - Pokemon Diamond %slash% Pearl %slash% Platinum - Galactic Boss Cyrus's comments (YT ID cvpGCTUGi8o).json"
echo "Archiving SD video 821, Best VGM 777 - Pokemon Silver %slash% Gold %slash% Crystal - Radio ~ Lucky Channel %slash% Game Corner's comments (YouTube id j16ZcZf9Xz8...)"
python downloader.py --youtubeid="j16ZcZf9Xz8" --output="SD0821 Best VGM 777 - Pokemon Silver %slash% Gold %slash% Crystal - Radio ~ Lucky Channel %slash% Game Corner's comments (YT ID j16ZcZf9Xz8).json"
echo "Archiving SD video 830, Best VGM 787 - Pokemon Black %slash% White - Route 10's comments (YouTube id _Gnu2AttTPI...)"
python downloader.py --youtubeid="_Gnu2AttTPI" --output="SD0830 Best VGM 787 - Pokemon Black %slash% White - Route 10's comments (YT ID _Gnu2AttTPI).json"
echo "Archiving SD video 873, Best VGM 829 - Pokemon Diamond %slash% Pearl %slash% Platinum - Snowpoint City (Midday)'s comments (YouTube id v02ZFogqSS8...)"
python downloader.py --youtubeid="v02ZFogqSS8" --output="SD0873 Best VGM 829 - Pokemon Diamond %slash% Pearl %slash% Platinum - Snowpoint City (Midday)'s comments (YT ID v02ZFogqSS8).json"
echo "Archiving SD video 888, Best VGM 843 - Super Mario Galaxy 2 - Square Timber %slash% Puzzle Plank Galaxy's comments (YouTube id SAWxsyvWcqs...)"
python downloader.py --youtubeid="SAWxsyvWcqs" --output="SD0888 Best VGM 843 - Super Mario Galaxy 2 - Square Timber %slash% Puzzle Plank Galaxy's comments (YT ID SAWxsyvWcqs).json"
echo "Archiving SD video 938, Best VGM 891 - Blast Corps - Echo Marches %slash% Havoc District's comments (YouTube id 46WQk6Qvne8...)"
python downloader.py --youtubeid="46WQk6Qvne8" --output="SD0938 Best VGM 891 - Blast Corps - Echo Marches %slash% Havoc District's comments (YT ID 46WQk6Qvne8).json"
echo "Archiving SD video 1019, Best VGM 973 - Super Mario Galaxy 2 - Magma Monster %slash% Melty Monster Galaxy's comments (YouTube id QtW1BBAufvM...)"
python downloader.py --youtubeid="QtW1BBAufvM" --output="SD1019 Best VGM 973 - Super Mario Galaxy 2 - Magma Monster %slash% Melty Monster Galaxy's comments (YT ID QtW1BBAufvM).json"
echo "Archiving SD video 1116, Best VGM 1064 - Breath of Death VII - Introduction  %slash% Desert (Calm Streams)'s comments (YouTube id w4b-3x2wqpw...)"
python downloader.py --youtubeid="w4b-3x2wqpw" --output="SD1116 Best VGM 1064 - Breath of Death VII - Introduction  %slash% Desert (Calm Streams)'s comments (YT ID w4b-3x2wqpw).json"
echo "Archiving SD video 1117, [SD Remix] Breath of Death VII - Introduction %slash% Desert's comments (YouTube id OdX5m9maRg4...)"
python downloader.py --youtubeid="OdX5m9maRg4" --output="SD1117 [SD Remix] Breath of Death VII - Introduction %slash% Desert's comments (YT ID OdX5m9maRg4).json"
echo "Archiving SD video 1189, Best VGM 1135 - Super Mario Galaxy 2 - Cloud Garden %slash% Fluffy Bluff Galaxy's comments (YouTube id HwBOvdH38l0...)"
python downloader.py --youtubeid="HwBOvdH38l0" --output="SD1189 Best VGM 1135 - Super Mario Galaxy 2 - Cloud Garden %slash% Fluffy Bluff Galaxy's comments (YT ID HwBOvdH38l0).json"
echo "Archiving SD video 1218, Best VGM 1163 - Pokemon Ruby %slash% Sapphire %slash% Emerald - Mt. Pyre's comments (YouTube id w_TOt-XQnPg...)"
python downloader.py --youtubeid="w_TOt-XQnPg" --output="SD1218 Best VGM 1163 - Pokemon Ruby %slash% Sapphire %slash% Emerald - Mt. Pyre's comments (YT ID w_TOt-XQnPg).json"
echo "Archiving SD video 1310, Best VGM 1251 - Mega Man - Dr. Wily Stage 1 %slash% 2 (Series' 25th Anniversary)'s comments (YouTube id k3m-_uCo-b8...)"
python downloader.py --youtubeid="k3m-_uCo-b8" --output="SD1310 Best VGM 1251 - Mega Man - Dr. Wily Stage 1 %slash% 2 (Series' 25th Anniversary)'s comments (YT ID k3m-_uCo-b8).json"
echo "Archiving SD video 1314, Best VGM 1255 - Pokemon Diamond %slash% Pearl %slash% Platinum - Route 216 (Day)'s comments (YouTube id bmsw4ND8HNA...)"
python downloader.py --youtubeid="bmsw4ND8HNA" --output="SD1314 Best VGM 1255 - Pokemon Diamond %slash% Pearl %slash% Platinum - Route 216 (Day)'s comments (YT ID bmsw4ND8HNA).json"
echo "Archiving SD video 1403, Best VGM 1345 - Pokemon Ruby %slash% Sapphire %slash% Emerald - Lilycove City's comments (YouTube id hBg-pnQpic4...)"
python downloader.py --youtubeid="hBg-pnQpic4" --output="SD1403 Best VGM 1345 - Pokemon Ruby %slash% Sapphire %slash% Emerald - Lilycove City's comments (YT ID hBg-pnQpic4).json"
echo "Archiving SD video 1404, Best VGM 1346 - Sonic CD - Quartz Quadrant ~ Present (JP %slash% EU)'s comments (YouTube id CYswIEEMIWw...)"
python downloader.py --youtubeid="CYswIEEMIWw" --output="SD1404 Best VGM 1346 - Sonic CD - Quartz Quadrant ~ Present (JP %slash% EU)'s comments (YT ID CYswIEEMIWw).json"
echo "Archiving SD video 1451, Best VGM 1394 - Blast Corps - Carrick Point %slash% Ebony Coast's comments (YouTube id 6l8a_pzRcRI...)"
python downloader.py --youtubeid="6l8a_pzRcRI" --output="SD1451 Best VGM 1394 - Blast Corps - Carrick Point %slash% Ebony Coast's comments (YT ID 6l8a_pzRcRI).json"
echo "Archiving SD video 1568, Best VGM 1514 - Pokemon X %slash% Y - The Kalos Power Plant's comments (YouTube id Y1i3z56CiU4...)"
python downloader.py --youtubeid="Y1i3z56CiU4" --output="SD1568 Best VGM 1514 - Pokemon X %slash% Y - The Kalos Power Plant's comments (YT ID Y1i3z56CiU4).json"
echo "Archiving SD video 1694, Best VGM 1645 - Super Smash Bros. Wii U %slash% 3DS - All-Star Rest Area's comments (YouTube id ECP710r6JCM...)"
python downloader.py --youtubeid="ECP710r6JCM" --output="SD1694 Best VGM 1645 - Super Smash Bros. Wii U %slash% 3DS - All-Star Rest Area's comments (YT ID ECP710r6JCM).json"
echo "Archiving SD video 1740, Best VGM 1692 - Pokemon Omega Ruby %slash% Alpha Sapphire - Dive's comments (YouTube id fpVag5b7zHo...)"
python downloader.py --youtubeid="fpVag5b7zHo" --output="SD1740 Best VGM 1692 - Pokemon Omega Ruby %slash% Alpha Sapphire - Dive's comments (YT ID fpVag5b7zHo).json"
echo "Archiving SD video 1749, Best VGM 1700 - Mario Kart 8 - Toad Harbor %slash% Toad's Turnpike's comments (YouTube id -J55bt2b3Z8...)"
python downloader.py --youtubeid="-J55bt2b3Z8" --output="SD1749 Best VGM 1700 - Mario Kart 8 - Toad Harbor %slash% Toad's Turnpike's comments (YT ID -J55bt2b3Z8).json"
echo "Archiving SD video 1764, [GOTY 2014 #9] Best VGM 1718 - Super Smash Bros Wii U %slash% 3DS - Chill Ver. 2 (Dr. Mario)'s comments (YouTube id zpleUx1Llgs...)"
python downloader.py --youtubeid="zpleUx1Llgs" --output="SD1764 [GOTY 2014 #9] Best VGM 1718 - Super Smash Bros Wii U %slash% 3DS - Chill Ver. 2 (Dr. Mario)'s comments (YT ID zpleUx1Llgs).json"
echo "Archiving SD video 1843, Best VGM 1800 - Pokemon - Route 1 %slash% Gym %slash% Wild Battle %slash% Route 101 %slash% Pokemon Center's comments (YouTube id 6b77tr2Vu9U...)"
python downloader.py --youtubeid="6b77tr2Vu9U" --output="SD1843 Best VGM 1800 - Pokemon - Route 1 %slash% Gym %slash% Wild Battle %slash% Route 101 %slash% Pokemon Center's comments (YT ID 6b77tr2Vu9U).json"
echo "Archiving SD video 2138, Best VGM 2104 - Pilotwings 64 - Replay %slash% Results's comments (YouTube id NuSPcCqiCZo...)"
python downloader.py --youtubeid="NuSPcCqiCZo" --output="SD2138 Best VGM 2104 - Pilotwings 64 - Replay %slash% Results's comments (YT ID NuSPcCqiCZo).json"
echo "Archiving SD video 2147, Best VGM 2114 - Black%slash%Matrix - Deboneir's comments (YouTube id dd2dbckq54Q...)"
python downloader.py --youtubeid="dd2dbckq54Q" --output="SD2147 Best VGM 2114 - Black%slash%Matrix - Deboneir's comments (YT ID dd2dbckq54Q).json"
echo "Archiving SD video 2231, Best VGM 2200 -  World of Warcraft - Tavern %slash% Main Theme's comments (YouTube id PRLWoJBwJFY...)"
python downloader.py --youtubeid="PRLWoJBwJFY" --output="SD2231 Best VGM 2200 -  World of Warcraft - Tavern %slash% Main Theme's comments (YT ID PRLWoJBwJFY).json"
echo "Archiving SD video 2311, Best VGM 2284 - Pokemon Silver %slash% Gold %slash% Crystal - Azalea Town's comments (YouTube id w4Kwk1rKzXM...)"
python downloader.py --youtubeid="w4Kwk1rKzXM" --output="SD2311 Best VGM 2284 - Pokemon Silver %slash% Gold %slash% Crystal - Azalea Town's comments (YT ID w4Kwk1rKzXM).json"
echo "Archiving SD video 2335, Best VGM 2307 - Pokemon Diamond %slash% Pearl %slash% Platinum - Oreburgh City (Night)'s comments (YouTube id dNjMJS8vc8g...)"
python downloader.py --youtubeid="dNjMJS8vc8g" --output="SD2335 Best VGM 2307 - Pokemon Diamond %slash% Pearl %slash% Platinum - Oreburgh City (Night)'s comments (YT ID dNjMJS8vc8g).json"
echo "Archiving SD video 2379, Best VGM 2352 - Pokemon SoulSilver %slash% HeartGold - National Park's comments (YouTube id xjHdaTMJMLY...)"
python downloader.py --youtubeid="xjHdaTMJMLY" --output="SD2379 Best VGM 2352 - Pokemon SoulSilver %slash% HeartGold - National Park's comments (YT ID xjHdaTMJMLY).json"
echo "Archiving SD video 2469, Best VGM 2446 - Pokemon Sword %slash% Shield - Route 's comments (YouTube id lM28rfsHge0...)"
python downloader.py --youtubeid="lM28rfsHge0" --output="SD2469 Best VGM 2446 - Pokemon Sword %slash% Shield - Route 's comments (YT ID lM28rfsHge0).json"
